package com.suyaphot.app.core.crypto

import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Helper for AES-256-GCM AEAD operations.
 */
object Aead {
    private const val GCM_TAG_LENGTH_BITS = 128
    const val NONCE_LENGTH_BYTES = 12

    fun generateNonce(): ByteArray {
        val nonce = ByteArray(NONCE_LENGTH_BYTES)
        SecureRandom().nextBytes(nonce)
        return nonce
    }

    fun encrypt(
        keyBytes: ByteArray,
        nonce: ByteArray,
        aad: ByteArray,
        plaintext: ByteArray
    ): ByteArray {
        val key: SecretKey = SecretKeySpec(keyBytes, "AES")
        return encrypt(key, nonce, aad, plaintext)
    }

    fun encrypt(
        key: SecretKey,
        nonce: ByteArray,
        aad: ByteArray,
        plaintext: ByteArray
    ): ByteArray {
        require(nonce.size == NONCE_LENGTH_BYTES) { "AES-GCM nonce must be 12 bytes" }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, nonce)
        cipher.init(Cipher.ENCRYPT_MODE, key, spec)
        if (aad.isNotEmpty()) {
            cipher.updateAAD(aad)
        }
        return cipher.doFinal(plaintext)
    }

    fun decrypt(
        keyBytes: ByteArray,
        nonce: ByteArray,
        aad: ByteArray,
        ciphertext: ByteArray
    ): ByteArray {
        val key: SecretKey = SecretKeySpec(keyBytes, "AES")
        return decrypt(key, nonce, aad, ciphertext)
    }

    fun decrypt(
        key: SecretKey,
        nonce: ByteArray,
        aad: ByteArray,
        ciphertext: ByteArray
    ): ByteArray {
        require(nonce.size == NONCE_LENGTH_BYTES) { "AES-GCM nonce must be 12 bytes" }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, nonce)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)
        if (aad.isNotEmpty()) {
            cipher.updateAAD(aad)
        }
        return cipher.doFinal(ciphertext)
    }

    /**
     * Convenience method that generates a random 12-byte nonce, prepends it to the ciphertext,
     * and returns: [12-byte nonce] + [ciphertext with 16-byte GCM tag].
     */
    fun encryptWithPrependedNonce(
        keyBytes: ByteArray,
        plaintext: ByteArray,
        aad: ByteArray = ByteArray(0)
    ): ByteArray {
        val nonce = generateNonce()
        val ciphertext = encrypt(keyBytes, nonce, aad, plaintext)
        return try {
            val result = ByteArray(nonce.size + ciphertext.size)
            System.arraycopy(nonce, 0, result, 0, nonce.size)
            System.arraycopy(ciphertext, 0, result, nonce.size, ciphertext.size)
            result
        } finally {
            ciphertext.fill(0)
        }
    }

    fun encryptWithPrependedNonce(
        key: SecretKey,
        plaintext: ByteArray,
        aad: ByteArray = ByteArray(0)
    ): ByteArray {
        // Android Keystore GCM keys reject caller-selected encryption IVs. Let the provider
        // generate one and serialize the actual IV returned by Cipher for decryption.
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        if (aad.isNotEmpty()) cipher.updateAAD(aad)
        val nonce = cipher.iv
        require(nonce.size == NONCE_LENGTH_BYTES) { "AES-GCM nonce must be 12 bytes" }
        val ciphertext = cipher.doFinal(plaintext)
        return try {
            ByteArray(nonce.size + ciphertext.size).also { result ->
                nonce.copyInto(result)
                ciphertext.copyInto(result, destinationOffset = nonce.size)
            }
        } finally {
            ciphertext.fill(0)
        }
    }

    /**
     * Decrypts a payload generated by [encryptWithPrependedNonce].
     */
    fun decryptWithPrependedNonce(
        keyBytes: ByteArray,
        payload: ByteArray,
        aad: ByteArray = ByteArray(0)
    ): ByteArray {
        require(payload.size >= NONCE_LENGTH_BYTES + 16) { "Payload is too short to be valid AEAD ciphertext" }
        val nonce = ByteArray(NONCE_LENGTH_BYTES)
        val ciphertext = ByteArray(payload.size - NONCE_LENGTH_BYTES)
        System.arraycopy(payload, 0, nonce, 0, NONCE_LENGTH_BYTES)
        System.arraycopy(payload, NONCE_LENGTH_BYTES, ciphertext, 0, ciphertext.size)
        return decrypt(keyBytes, nonce, aad, ciphertext)
    }

    fun decryptWithPrependedNonce(
        key: SecretKey,
        payload: ByteArray,
        aad: ByteArray = ByteArray(0)
    ): ByteArray {
        require(payload.size >= NONCE_LENGTH_BYTES + 16) { "Payload is too short to be valid AEAD ciphertext" }
        val nonce = payload.copyOfRange(0, NONCE_LENGTH_BYTES)
        val ciphertext = payload.copyOfRange(NONCE_LENGTH_BYTES, payload.size)
        return decrypt(key, nonce, aad, ciphertext)
    }
}
